#DatabBase
DATABASE_USER_NAME: user
DATABASE_PASSWORD: user

#Server
SERVER_PORT: 8080
ACTIVE_PROFILE: dev
#Logging
LOGGING_PATH: /
LOGGING_FILE_NAME: myLog.txt

#Email Config

EMAIL_HOST : smtp.gmail.com
EMAIL_PORT : 587
EMAIL_ID : <YOUR GMAIL MAIL>
EMAIL_PASSWORD : <YOUR API PASSWORD>
VERIFY_EMAIL_HOST : http://localhost:${server.port}